In [4]:
import sqlite3
import pandas as pd
from pathlib import Path

# Dynamic path: go up one level from scripts/ to reach the project root, then into files/
# db_path = Path(__file__).parent.parent / "files" / "cepel_data.db"

# In a Jupyter notebook, use this instead:
db_path = Path.cwd().parent / "files" / "cepel_data.db"
conn = sqlite3.connect(str(db_path))
# Show full column content (no truncation with "...")
pd.set_option('display.max_colwidth', None)
# List all tables in the SQLite database
tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)
print(tables)

                                                                             name
0                                                                       joined_df
1     Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_21
2             Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_1_Geral1_19
3          Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_2_Avançada1_19
4  Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_3_Interface_DevOps1_18

In [ ]:
# Carrega um recorte da tabela de identificação dos respondentes
table1 = pd.read_sql_query('''SELECT * FROM Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_21''', conn)

import pandas as pd

def SENIORIDADE_TEMPO_DE_CASA_NO_CEPEL(exp):
    if exp in ['Menos de 1 ano', '1-2 anos']:
        return 'Junior'
    elif exp in ['3-5 anos']:
        return 'Pleno'
    elif exp in ['6-10 anos','11-15 anos', '16-20 anos', '21-25 anos']:
        return 'Senior'
    else:
        return 'Outro'

table1['SENIORIDADE_TEMPO_DE_CASA_NO_CEPEL'] = table1['FAVOR_APONTAR_O_SEU_TEMPO_DE_CASA_NO_CEPEL'].apply(SENIORIDADE_TEMPO_DE_CASA_NO_CEPEL)



def HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS(exp):
    if exp in ['Menos de 1 ano', '1-2 anos']:
        return 'Junior'
    elif exp in ['3-5 anos']:
        return 'Pleno'
    elif exp in ['5-10 anos','Mais de 10 anos']:
        return 'Senior'
    else:
        return 'Outro'

table1['SENIORIDADE_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS'] = table1['HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS'].apply(HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS)



def HA_QUANTO_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS(exp):
    if exp in ['Menos de 1 ano', '1-2 anos']:
        return 'Junior'
    elif exp in ['3-5 anos']:
        return 'Pleno'
    elif exp in ['5-10 anos', 'Mais de 10 anos']:
        return 'Senior'
    else:
        return 'Outro'

table1['SENIORIDADE_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS'] = table1['HA_QUANTO_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS'].apply(HA_QUANTO_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS)



#table1[['SENIORIDADE_TEMPO_DE_CASA_NO_CEPEL','FAVOR_APONTAR_O_SEU_TEMPO_DE_CASA_NO_CEPEL']]
#table1[['SENIORIDADE_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS','HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS']]

,SENIORIDADE_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS,HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS
0,Senior,5-10 anos
1,Pleno,3-5 anos
2,Senior,5-10 anos
3,Senior,5-10 anos
4,Senior,Mais de 10 anos
5,Senior,5-10 anos
6,Senior,5-10 anos
7,Senior,5-10 anos
8,Pleno,3-5 anos
9,Senior,Mais de 10 anos
10,Junior,1-2 anos
11,Junior,Menos de 1 ano
12,Senior,Mais de 10 anos
13,Junior,Menos de 1 ano
14,Senior,5-10 anos
15,Senior,Mais de 10 anos
16,Senior,Mais de 10 anos
17,Pleno,3-5 anos
18,Pleno,3-5 anos
19,Junior,1-2 anos
20,Senior,Mais de 10 anos

In [ ]:
# table1['FAVOR_APONTAR_SUA_FAIXA_ETARIA'].unique()
# ['25-34 anos', '35-44 anos', '45-54 anos', '18-24 anos'],não representa a serionidade

# table1['FAVOR_APONTAR_SEU_MAIOR_NIVEL_DE_FORMACAO_EDUCACIONAL'].unique()
# ['Especialização','Graduação','Mestrado / MBA','Doutorado','Ensino médio / profissionalizante']

<ArrowStringArray>
[                   'Especialização',                         'Graduação',
                    'Mestrado / MBA',                         'Doutorado',
 'Ensino médio / profissionalizante']
Length: 5, dtype: str

In [33]:
table1.head(5)

,ID,START_TIME,COMPLETION_TIME,EMAIL,NAME,LAST_MODIFIED_TIME,FAVOR_INSERIR_SEU_NOME_COMPLETO,FAVOR_INSERIR_SEU_EMAIL_CEPELBR,EM_QUAL_DEPARTAMENTO_DO_CEPEL_VOCE_ESTA_ALOCADO,FAVOR_APONTAR_SUA_FAIXA_ETARIA,FAVOR_APONTAR_O_SEU_TEMPO_DE_CASA_NO_CEPEL,FAVOR_APONTAR_SEU_MAIOR_NIVEL_DE_FORMACAO_EDUCACIONAL,HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS,HA_QUANTO_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS,SENIORIDADE_TEMPO_DE_CASA_NO_CEPEL,SENIORIDADE_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS,SENIORIDADE_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS
0,6,2026-03-03 10:50:23,2026-03-03 10:51:24,0335009@cepel.br,Pedro Cesar de Oliveira,None,Pedro César Miguel de Oliveira,pedrocesar@cepel.br,DT/DTS - Depto de Transição Energética e Sustentabilidade,25-34 anos,6-10 anos,Especialização,5-10 anos,3-5 anos,Senior,Senior,Pleno
1,7,2026-03-03 10:51:09,2026-03-03 10:52:20,0360841@cepel.br,Nério José Fernandes dos Santos,None,Nério José Fernandes dos Santos,nerio.santos@cepel.br,DT/DTS - Depto de Transição Energética e Sustentabilidade,25-34 anos,3-5 anos,Graduação,3-5 anos,3-5 anos,Pleno,Pleno,Pleno
2,8,2026-03-03 10:57:39,2026-03-03 10:58:59,0360710@cepel.br,Marcelo Alberto Guimarães,None,Marcelo Alberto Guimarães,marcelo.guimaraes@cepel.br,"DT/DPC - Depto de Planejamento Energético, Comercialização de Energia e Regulação",35-44 anos,1-2 anos,Mestrado / MBA,5-10 anos,5-10 anos,Junior,Senior,Senior
3,9,2026-03-03 11:06:55,2026-03-03 11:08:25,0360099@cepel.br,Guilherme Prudente Da Silva,None,Guilherme Prudente da Silva,guilherme.silva@cepel.br,DT/DGA - Depto de Tecnologia em Gestão de Ativos,25-34 anos,1-2 anos,Mestrado / MBA,5-10 anos,3-5 anos,Junior,Senior,Pleno
4,10,2026-03-03 11:04:51,2026-03-03 11:09:05,brunaf@cepel.br,Bruna de Andrade Bastos Fonseca,None,Bruna de Andrade Bastos Fonseca,brunaf@cepel.br,DT/DGA - Depto de Tecnologia em Gestão de Ativos,35-44 anos,11-15 anos,Especialização,Mais de 10 anos,Menos de 1 ano,Senior,Senior,Junior

In [63]:
table4 = pd.read_sql_query('''SELECT * FROM Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_3_Interface_DevOps1_18''', conn)

grupos = {

    "SISTEMA_OPERACIONAL": [
        "WINDOWS_NT_SERVER",
        "WINDOWS_1011",
        "LINUX_DEBIAN_UBUNTU_MINT_KALI",
        "LINUX_ARCH_MANJARO_ENDEAVOUROS",
        "LINUX_RED_HAT_FEDORA_CENTOS_ROCKY",
        "LINUX_SUSE",
        "LINUX_ALPINE",
        "MACOS",
        "CHROME_OS",
        "ANDROID",
        "IOS",
        "OUTRO6"
    ],

    "SISTEMA_OPERACIONAL_OUTRO": [
        "SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_SISTEMA_OPERACIONAL_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO"
    ],

    "SISTEMA_OPERACIONAL_PRIORITARIO": [
        "QUAIS_DOS_SEGUINTES_SISTEMAS_OPERACIONAIS_LHE_SAO_PRIORITARIOS"
    ],

    "VIRTUALIZACAO_E_ACESSO": [
        "SSH",
        "RDP_WINDOWS",
        "VNC_MULTIPLATAFORMA",
        "WSL_WINDOWS_SUBSYSTEM_FOR_LINUX",
        "VMWARE",
        "VIRTUALBOX",
        "PROXMOX",
        "DOCKER",
        "PODMAN",
        "SINGULARITY",
        "DOCKERCOMPOSE",
        "DOCKERSWARM",
        "KUBERNETES",
        "OUTRO7"
    ],

    "VIRTUALIZACAO_OUTRO": [
        "SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_MODELO_DE_VIRTUALIZACAO_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO"
    ],

    "VIRTUALIZACAO_PRIORITARIO": [
        "QUAIS_DOS_SEGUINTES_MODELOS_DE_VIRTUALIZACAO_OU_DE_ACESSO_VIRTUAL_A_RECURSOS_LHE_SAO_PRIORITARIOS"
    ],

    "LINGUAGEM_PROGRAMACAO": [
        "SQL",
        "PYTHON",
        "R",
        "SCALA",
        "JAVA",
        "JAVASCRIPT",
        "TYPESCRIPT",
        "SHELL_SCRIPT",
        "PHP",
        "RUBY",
        "GO",
        "RUST",
        "C_E_C",
        "C",
        "JULIA",
        "FORTRAN",
        "MATLAB",
        "LABVIEW2",
        "OUTRA"
    ],

    "LINGUAGEM_OUTRA": [
        "SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRA_LINGUAGEM_DE_PROGRAMACAO_VOLTADA_A_DADOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO"
    ],

    "LINGUAGEM_PRIORITARIA": [
        "QUAIS_DAS_SEGUINTES_LINGUAGENS_DE_PROGRAMACAO_VOLTADAS_A_DADOS_LHE_SAO_PRIORITARIAS"
    ],

    "IDES_E_FERRAMENTAS_DEV": [
        "MS_VISUAL_STUDIO",
        "VS_CODE",
        "CURSOR",
        "ANTIGRAVITY",
        "ECLIPSE",
        "INTELLIJ_IDEA",
        "NETBEAMS",
        "PYCHARM",
        "SUBLIME",
        "VIM",
        "EMACS",
        "LABVIEW",
        "CODER_CDE",
        "JUPYTER_LABNOTEBOOK",
        "GITHUB_CODESPACES",
        "KAGGLE_NOTEBOOKS",
        "GOOGLE_COLABORATORY",
        "BACKSTAGE_IDP",
        "OPSLEVEL",
        "COMPASS",
        "PORT",
        "OUTRO10"
    ],

    "IDES_OUTRO": [
        "SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_DESENVOLVIMENTO_DE_SOFTWAREDADOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO"
    ],

    "IDES_PRIORITARIO": [
        "QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_DESENVOLVIMENTO_DE_SOFTWAREDADOS_LHE_SAO_PRIORITARIOS"
    ],

    "CONTROLE_DE_VERSAO": [
        "CVS_CONCURRENT_VERSION_SYSTEM",
        "SVN_APACHE_SUBVERSION",
        "MERCURIAL",
        "GIT_GITHUB",
        "GIT_GITLAB",
        "GIT_BITBUCKET",
        "GIT_LFS_LARGE_FILE_STORAGE",
        "DVC_DATA_VERSION_CONTROL",
        "LAKEFS",
        "OUTRO2"
    ],

    "CONTROLE_VERSAO_OUTRO": [
        "SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_CONTROLE_DE_VERSAO_DE_SOFTWAREDADOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO"
    ],

    "CONTROLE_VERSAO_PRIORITARIO": [
        "QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_CONTROLE_DE_VERSAO_DE_SOFTWAREDADOS_LHE_SAO_PRIORITARIOS"
    ],

    "INFRAESTRUTURA_COMO_CODIGO": [
        "TERRAFORM",
        "OPENTOFU",
        "PULUMI",
        "CROSSPLANE",
        "ANSIBLE",
        "PUPPET",
        "CHEF",
        "SALT",
        "NORNIR",
        "VAGRANT",
        "OUTRO5"
    ],

    "CI_CD": [
        "JENKINS",
        "TRAVIS_CI",
        "CIRCLE_CI",
        "GITHUB_ACTIONS",
        "GITLAB_CICD",
        "TEAMCITY",
        "BITBUCKET_PIEPELINES",
        "FLUXCD",
        "ARGOCD",
        "OCTOPUSDEPLOY",
        "OUTRO3"
    ],

    "METODOLOGIAS_GESTAO": [
        "PMBOK",
        "SWEBOK",
        "DMBOK",
        "KANBAN",
        "SCRUM",
        "EXTREME_PROGRAMMING_XP",
        "SAFE",
        "OUTRO"
    ],

    "BOAS_PRATICAS_ENGENHARIA": [
        "DEVOPS",
        "DEVSECOPS_OWASP_TOP_10",
        "DATAOPS",
        "MLOPS",
        "CLEAN_ARCHITECTURE_E_CLEAN_CODE",
        "DDD_DOMAINDRIVEN_DESIGN",
        "DESIGN_PATTERNS",
        "BDD_BEHAVIORDRIVEN_DESIGN",
        "TDD_TESTDRIVEN_DEVELOPMENT",
        "CRISPDM",
        "PRINCIPIOS_SOLID",
        "PRINCIPIOS_KISS",
        "PRINCIPIOS_YAGNI",
        "REFACTORING",
        "THE_TWELVEFACTOR_APP",
        "OUTRO9"
    ],

    "FERRAMENTAS_GESTAO_PROJETOS": [
        "SCOPI",
        "BSC_DESIGNER",
        "TRELLO",
        "PLANNER",
        "CLICKUP",
        "JIRA",
        "LINEAR",
        "GLPI",
        "MANTIS",
        "BUGZILLA",
        "OUTRO4"
    ],

    "DOCUMENTACAO_COLABORACAO": [
        "MS_SHAREPOINT",
        "CONFLUENCE",
        "NOTION",
        "MONDAYCOM",
        "MIRO",
        "MS_WHITEBOARD",
        "SLACK",
        "MS_TEAMS",
        "DOXYGEN",
        "DRAWIO",
        "PLANTUML",
        "SWAGGER",
        "CKAN",
        "RESTRUCTUREDTEXT_REST",
        "SPHINX",
        "MKDOCS",
        "READ_THE_DOCS",
        "KEEP_A_CHANGELOG",
        "SCRIBE",
        "OBS_STUDIO",
        "OUTRO8"
    ]
}

id_cols = ["ID", "EMAIL", "NAME"]

dfs = []

# grupos.items() -> it will return a view object that displays a list of a dictionary's key-value tuple pairs.
# dict_items([('SISTEMA_OPERACIONAL', ['WINDOWS_NT_SERVER', 'WINDOWS_1011', 'LINUX_DEBIAN_UBUNTU_MINT_KALI', 'LINUX_A....

for categoria, cols in grupos.items():

    df_temp = table4.melt(
        id_vars=id_cols,
        value_vars=cols,
        var_name="TECNOLOGIA",
        value_name="RESPOSTA"
    )

    df_temp["CATEGORIA"] = categoria

    dfs.append(df_temp)

df_final = pd.concat(dfs, ignore_index=True)

# Replacing Regex r"OUTRO\d+"
df_final["TECNOLOGIA"] = df_final["TECNOLOGIA"].str.replace(r"OUTRO\d+", "OUTRO", regex=True)

In [64]:
resultado = (
    table1
    .merge(
        df_final.drop(columns=["ID","EMAIL"], errors="ignore"),
        on="NAME",
        how="left"
    )
)

In [72]:
'''
# Calcuting total values for each category, department, seniority and technology

dfs_resultados = {}

for categoria in grupos.keys():

    df_result = (
        resultado[resultado["CATEGORIA"] == categoria]
        .groupby(["EM_QUAL_DEPARTAMENTO_DO_CEPEL_VOCE_ESTA_ALOCADO","HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS","TECNOLOGIA"])
        .size()
        .reset_index(name="TOTAL")
    )
    df_result

    #import pandas as pd

    # Salvando de forma básica
    #df_result.to_csv(f'{categoria}.csv', index=False)

    #print(f"Arquivo salvo como '{categoria}.csv'")

'''

'\n# Calcuting total values for each category, department, seniority and technology\n\ndfs_resultados = {}\n\nfor categoria in grupos.keys():\n\n    df_result = (\n        resultado[resultado["CATEGORIA"] == categoria]\n        .groupby(["EM_QUAL_DEPARTAMENTO_DO_CEPEL_VOCE_ESTA_ALOCADO","HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS","TECNOLOGIA"])\n        .size()\n        .reset_index(name="TOTAL")\n    )\n    df_result\n\n    #import pandas as pd\n\n    # Salvando de forma básica\n    #df_result.to_csv(f\'{categoria}.csv\', index=False)\n\n    #print(f"Arquivo salvo como \'{categoria}.csv\'")\n\n'

In [65]:
# resultado

In [66]:
# Calcuting total values for each category, department, seniority and technology

#df_result = resultado.groupby(["NAME","EM_QUAL_DEPARTAMENTO_DO_CEPEL_VOCE_ESTA_ALOCADO"]).size().reset_index(name="TOTAL")
#df_result = resultado.groupby(["SENIORIDADE_TEMPO_DE_CASA_NO_CEPEL",
#                               "SENIORIDADE_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS",
#                               "EM_QUAL_DEPARTAMENTO_DO_CEPEL_VOCE_ESTA_ALOCADO",]).size().reset_index(name="TOTAL")

In [67]:
resultado.columns

Index(['ID', 'START_TIME', 'COMPLETION_TIME', 'EMAIL', 'NAME',
       'LAST_MODIFIED_TIME', 'FAVOR_INSERIR_SEU_NOME_COMPLETO',
       'FAVOR_INSERIR_SEU_EMAIL_CEPELBR',
       'EM_QUAL_DEPARTAMENTO_DO_CEPEL_VOCE_ESTA_ALOCADO',
       'FAVOR_APONTAR_SUA_FAIXA_ETARIA',
       'FAVOR_APONTAR_O_SEU_TEMPO_DE_CASA_NO_CEPEL',
       'FAVOR_APONTAR_SEU_MAIOR_NIVEL_DE_FORMACAO_EDUCACIONAL',
       'HA_QUANTO_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS',
       'HA_QUANTO_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS',
       'SENIORIDADE_TEMPO_DE_CASA_NO_CEPEL',
       'SENIORIDADE_TEMPO_VOCE_JA_PROGRAMA_DESENVOLVE_SISTEMAS',
       'SENIORIDADE_TEMPO_VOCE_JA_TRABALHA_COM_DADOS_GOVERNANCA_ENGENHARIA_CIENCIA_OU_ANALISE_DE_DADOS',
       'TECNOLOGIA', 'RESPOSTA', 'CATEGORIA'],
      dtype='str')

In [ ]:
# Salvando de forma básica

resultado.to_csv(f'doc4.csv', index=False)
print(f"Arquivo salvo como doc4.csv")

Arquivo salvo como doc4.csv

In [75]:
# Carrega um recorte da tabela de identificação dos respondentes
table3 = pd.read_sql_query('''SELECT * FROM Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_2_Avançada1_19''', conn)
table3.columns

Index(['ID', 'START_TIME', 'COMPLETION_TIME', 'EMAIL', 'NAME',
       'LAST_MODIFIED_TIME', 'BLOCK_STORAGE', 'FILE_STORAGE', 'OBJECT_STORAGE',
       'QUAIS_DOS_SEGUINTES_FORMATOS_PARA_ARMAZENAMENTO_E_GESTAO_DE_DADOS_LHE_SAO_PRIORITARIOS',
       ...
       'ELK_STACK_ELASTIC_LOGSTASH_KIBANA', 'GRAPHITE', 'FLUENTD', 'SPLUNK',
       'NEW_RELIC', 'DATADOG', 'AMBARI', 'OUTRO2',
       'SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_MONITORAMENTO_DE_DADOSRECURSOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO',
       'QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_MONITORAMENTO_DE_DADOSRECURSOS_LHE_SAO_PRIORITARIOS'],
      dtype='str', length=116)

In [76]:
print(table3.columns.tolist())

['ID', 'START_TIME', 'COMPLETION_TIME', 'EMAIL', 'NAME', 'LAST_MODIFIED_TIME', 'BLOCK_STORAGE', 'FILE_STORAGE', 'OBJECT_STORAGE', 'QUAIS_DOS_SEGUINTES_FORMATOS_PARA_ARMAZENAMENTO_E_GESTAO_DE_DADOS_LHE_SAO_PRIORITARIOS', 'DATA_WAREHOUSE', 'DATA_LAKE', 'DATA_LAKEHOUSE', 'DATA_FABRIC', 'DATA_MESH', 'QUAIS_DAS_SEGUINTES_ARQUITETURAS_PARA_ARMAZENAMENTO_E_GESTAO_DE_DADOS_LHE_SAO_PRIORITARIAS', 'APACHE_HADOOP_HDFS', 'GLUSTERFS', 'JUICEFS', 'MINIO', 'CEPH', 'GARAGE', 'APACHE_OZONE', 'APACHE_HUDI', 'APACHE_ICEBERG', 'DELTA_LAKE', 'DATABRICKS', 'SNOWFLAKE', 'DREMIO', 'STARBURST', 'OUTRO5', 'SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO', 'QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_PARA_ARMAZENAMENTO_E_GESTAO_DE_DADOS_LHE_SAO_PRIORITARIOS', 'OPENMETADATA', 'APACHE_ATLAS', 'AMUNDSEN', 'DATAHUB', 'MARQUEZ', 'CKAN', 'ATLAN', 'ALATION', 'COLLIBRA', 'IMMUTA', 'HIVE_METASTORE', 'UNITY_CATALOG', 'POLARIS_CATALOG', 'OUTRO3', 'SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_GOVERNANCA_E_GESTAO_DE_DADOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO', 'QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_GOVERNANCA_E_GESTAO_DE_DADOS_LHE_SAO_PRIORITARIOS', 'HASHICORP_VAULT', 'AKEYLESS', 'DOPPLER', 'INFISICAL', 'OPENBAO', 'KEYCLOAK', 'KERBEROS', 'OKTA', 'AUTHENTIK', 'OPA_OPEN_POLICY_AGENT', 'KYVERNO', 'CERBOS', 'APACHE_RANGER', 'APACHE_KNOX', 'SONAR_QUBE', 'OWASP', 'SNYK', 'GREMLIN', 'OUTRO6', 'SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_SEGURANCA_DE_DADOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO', 'QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_SEGURANCA_DE_DADOS_LHE_SAO_PRIORITARIOS', 'APACHE_AIRFLOW', 'PREFECT', 'DAGSTER', 'LUIGI', 'FLYTE', 'KESTRA', 'MAGE', 'MAESTRO', 'MLRUN', 'METAFLOW', 'KEDRO', 'ARGO_WORKFLOWS', 'JENKINS', 'OUTRO4', 'SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_ORQUESTRACAO_DE_DADOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO', 'QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_ORQUESTRACAO_DE_DADOS_LHE_SAO_PRIORITARIOS', 'MONTE_CARLO', 'SODA', 'GREAT_EXPECTATIONS', 'PANDERA', 'METAPLANE', 'BIGEYE', 'APACHE_GRIFFIN', 'ANOMALO', 'DATAFOLD', 'KENSU', 'ACCELDATA', 'LIGHTUP', 'OUTRO', 'SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_CONFORMIDADE_DE_DADOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO', 'QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_CONFORMIDADE_DE_DADOS_LHE_SAO_PRIORITARIOS', 'ZABBIX', 'OPENTELEMETRY', 'PROMETHEUS', 'GRAFANA', 'JAEGER', 'ELK_STACK_ELASTIC_LOGSTASH_KIBANA', 'GRAPHITE', 'FLUENTD', 'SPLUNK', 'NEW_RELIC', 'DATADOG', 'AMBARI', 'OUTRO2', 'SE_VOCE_APONTOU_TER_USADO_USAR_ATUALMENTE_OU_QUERER_USAR_OUTRO_FRAMEWORKFERRAMENTA_DE_MONITORAMENTO_DE_DADOSRECURSOS_ACIMA_POR_FAVOR_IDENTIFIQUE_QUAL_ABAIXO', 'QUAIS_DOS_SEGUINTES_FRAMEWORKSFERRAMENTAS_DE_MONITORAMENTO_DE_DADOSRECURSOS_LHE_SAO_PRIORITARIOS']